### ISSUE TITLE
Installation docs

### ISSUE THREAD

**Issue by mazzorini** [raffaelj/CpMultiplane#1]
Hi,

please provide a documentation how to setup cockpit for CpMultiplane (Fields for singletons, collections, etc..).

**Comment by raffaelj** [comment]
I write the docs/a tutorial right now and update the page with my settings live. This is also my first test on a remote host with completely fresh settings. I always copied and pasted samples from test installations before. Stay tuned :-)

https://monoplane.rlj.me

**Comment by mazzorini** [comment]
danke! 
Hast du auch ein kleines Beispiel für den Blog?

**Comment by raffaelj** [comment]
I wrote two tutorials today. One for installing the EditorFormats addon and using the wysiwyg editor and one for a simple blog with the one-collection-per-type method. More tutorials will follow when I find some time.

Wysiwyg and Editor Formats:
https://monoplane.rlj.me/en/blog/wysiwyg-configuration-editorformats-and-getimage-plugin

Simple Blog:
https://monoplane.rlj.me/en/blog/how-to-create-a-simple-blog

> Hast du auch ein kleines Beispiel für den Blog?

Ja - ist gerade fertig geworden. Du kannst gern auf Deutsch fragen, aber mich verwirrt das immer ein bisschen... Amtssprache auf Github ist Englisch und mein Kopf stellt sich mittlerweile automatisch um, sobald ich meinen Editor öffne. Also nicht wundern, wenn ich auf Englisch antworte.
